### ISSUE TITLE
Help Wanted: Create CONTRIBUTING.md file for our repository

### ISSUE THREAD

**Issue by MohammedHamzaMalik** [MohammedHamzaMalik/data-science-pipeline-playground#1]
## Create CONTRIBUTING.md File

We need help creating a comprehensive CONTRIBUTING.md file for our Data Science Pipeline Playground repository. This file will guide new contributors on how to participate in our project effectively.

### Objective

Create a well-structured CONTRIBUTING.md file that covers:

1. Introduction and welcome message
2. Code of Conduct reference
3. How to contribute:
   - Reporting bugs
   - Suggesting enhancements
   - Submitting pull requests
4. Style guides for:
   - Git commit messages
   - Python code (PEP 8)
   - Documentation
5. Labels used in the project
6. Any other relevant information for contributors

### Requirements

- The file should be written in Markdown format
- Content should be clear, concise, and welcoming to new contributors
- It should align with the goals and structure of our Data Science Pipeline Playground

### Additional Notes

- Feel free to look at CONTRIBUTING.md files from other popular data science repositories for inspiration
- Consider the diverse skill levels of potential contributors, from beginners to experts

### How to Contribute

If you're interested in taking on this task:

1. Comment on this issue to express your interest
2. Fork the repository
3. Create a new branch for this task
4. Create the CONTRIBUTING.md file
5. Submit a pull request with your proposed CONTRIBUTING.md

We appreciate any help in making our project more accessible and contributor-friendly!

Labels: documentation, help wanted, good first issue

**Comment by NidhiNayak08** [comment]
i will do this

**Comment by EzazAA** [comment]
I can i do that, If you prefer more engaging and beautiful text,, you might reach me out

**Comment by MohammedHamzaMalik** [comment]
> i will do this

Ok I will assign you

**Comment by MohammedHamzaMalik** [comment]
> I can i do that, If you prefer more engaging and beautiful text,, you might reach me out

I have assigned this issue to @NidhiNayak08 as she came first, she has two days to complete the task if she doesn't then I will assign it to you, or if you want you can work on other issues
