### ISSUE TITLE
Add an Intermediate Level Data Science Project

### ISSUE THREAD

**Issue by MohammedHamzaMalik** [MohammedHamzaMalik/data-science-pipeline-playground#4]
### Objective

Develop an intermediate-level data science project. This project should include:

- Data preprocessing and transformation
- Model selection and training
- Evaluation of model performance
- Visualizations of results

### Requirements

- Use libraries like pandas, numpy, scikit-learn, or similar
- Include a README.md with detailed instructions
- Ensure code is well-documented and follows PEP 8 guidelines

### How to Contribute

1. Fork the repository
2. Create a new branch: `git checkout -b intermediate-project`
3. Add your project in the `intermediate` directory
4. Submit a pull request with your changes

Labels: intermediate, help wanted

**Comment by sharayuanuse** [comment]
Can I work on this issue?

**Comment by MohammedHamzaMalik** [comment]
Yeah sure

**Comment by MohammedHamzaMalik** [comment]
Hey @sharayuanuse , please give update of your work

**Comment by sharayuanuse** [comment]
I am working on a Time Series Modeling project to analyze and forecast retail sales in the USA. I would be implementing KPSS and Dickey-Fuller tests to check stationarity and use ACF, PACF plots to estimate model parameters.

**Comment by MohammedHamzaMalik** [comment]
Ok good!
